/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormProduto.java
 *
 * Created on 09/04/2012, 21:44:38
 */
package br.com.dcoracoes.client.telas.produto;

import br.com.dcoracoes.client.ControleAcesso;
import br.com.dcoracoes.client.interfaces.InterfaceCadastroCompleto;
import br.com.dcoracoes.client.swingworker.SwingWorkerProduto;
import br.com.dcoracoes.client.util.LogUtil;
import br.com.dcoracoes.client.util.MensagensUtil;
import br.com.dcoracoes.client.util.MetodosUtil;
import br.com.dcoracoes.client.util.message.MessageProduto;
import br.com.dcoracoes.servico.service.*;
import java.awt.Component;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.lang.Exception;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author Cleberson
 */
public class FormProduto extends javax.swing.JFrame implements InterfaceCadastroCompleto {

    private Produto produto;

    public Produto getProduto() {
        return produto;
    }

    public void setProduto(Produto produto) {
        this.produto = produto;
        popularTela();

        disableTela(false);
        btnSalvar.setEnabled(false);
        btnEditar.setEnabled(ControleAcesso.ATIVA_BTN_CADASTRAR_PRODUTO);
        btnExcluir.setEnabled(ControleAcesso.ATIVA_BTN_DELETAR_PRODUTO);

    }

    /**
     * Creates new form FormProduto
     */
    public FormProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSuperButton = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtCodigoProFiscal = new javax.swing.JTextField();
        txtCodigoFornecedor = new javax.swing.JTextField();
        txtCodigoForFiscal = new javax.swing.JTextField();
        txtEstoqueTotal = new javax.swing.JTextField();
        txtCodigoBarras = new javax.swing.JTextField();
        txtReferenciaCatalogo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtxtPrecoVenda = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jtxtPrecoCusto = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        txtFornecedor = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableInfCores = new javax.swing.JTable();
        btnRemoverCor = new javax.swing.JButton();
        btnNovaCor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Produto");
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage("src/main/resources/imagens/outras/icon_SGC.gif"));
        setResizable(false);

        panelSuperButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(43, 115, 186)));

        btnNovo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/32x32/document-new.png"))); // NOI18N
        btnNovo.setText("NOVO");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/32x32/img_edit_32x32.png"))); // NOI18N
        btnEditar.setText("EDITAR");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/32x32/img_salvar_32x32.png"))); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnPesquisar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/32x32/system-search.png"))); // NOI18N
        btnPesquisar.setText("PESQUISAR");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnSair.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/32x32/sair32x32.png"))); // NOI18N
        btnSair.setText("SAIR");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/32x32/img_deletar_32x32.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jPanel4.setPreferredSize(new java.awt.Dimension(40, 60));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.setPreferredSize(new java.awt.Dimension(40, 60));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        jPanel9.setPreferredSize(new java.awt.Dimension(40, 60));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel10.setPreferredSize(new java.awt.Dimension(40, 60));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel11.setPreferredSize(new java.awt.Dimension(40, 60));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel12.setPreferredSize(new java.awt.Dimension(40, 60));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelSuperButtonLayout = new javax.swing.GroupLayout(panelSuperButton);
        panelSuperButton.setLayout(panelSuperButtonLayout);
        panelSuperButtonLayout.setHorizontalGroup(
            panelSuperButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 13, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 13, Short.MAX_VALUE)
                .addGap(7, 7, 7)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 13, Short.MAX_VALUE)
                .addGap(7, 7, 7)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 13, Short.MAX_VALUE)
                .addGap(7, 7, 7)
                .addComponent(btnPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 13, Short.MAX_VALUE)
                .addGap(7, 7, 7)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panelSuperButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelSuperButtonLayout.createSequentialGroup()
                    .addGap(147, 147, 147)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 13, Short.MAX_VALUE)
                    .addGap(777, 777, 777)))
        );
        panelSuperButtonLayout.setVerticalGroup(
            panelSuperButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSuperButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSuperButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addGroup(panelSuperButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelSuperButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelSuperButtonLayout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addGap(11, 11, 11)))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("REFERÊNCIA CATÁLOGO");

        txtCodigoProFiscal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigoProFiscal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoProFiscalKeyReleased(evt);
            }
        });

        txtCodigoFornecedor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigoFornecedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoFornecedorKeyReleased(evt);
            }
        });

        txtCodigoForFiscal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigoForFiscal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoForFiscalKeyReleased(evt);
            }
        });

        txtEstoqueTotal.setEditable(false);
        txtEstoqueTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtCodigoBarras.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigoBarras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoBarrasKeyReleased(evt);
            }
        });

        txtReferenciaCatalogo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtReferenciaCatalogo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtReferenciaCatalogoKeyReleased(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("ESTOQUE TOTAL");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("CÓDIGO BARRAS");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CÓDIGO FORFISCAL");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CÓDIGO FORNECEDOR");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CÓDIGO PROFISCAL");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("PREÇO DE VENDA");

        jtxtPrecoVenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jtxtPrecoVenda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtPrecoVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtPrecoVendaKeyReleased(evt);
            }
        });

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("PREÇO DE CUSTO");

        jtxtPrecoCusto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jtxtPrecoCusto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtPrecoCusto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtPrecoCustoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtReferenciaCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCodigoFornecedor)
                            .addComponent(txtCodigoBarras)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtCodigoForFiscal, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCodigoProFiscal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtEstoqueTotal)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtxtPrecoCusto)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtPrecoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtReferenciaCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigoProFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigoForFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEstoqueTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtFornecedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFornecedorFocusLost(evt);
            }
        });
        txtFornecedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFornecedorKeyReleased(evt);
            }
        });

        txtDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescricaoKeyReleased(evt);
            }
        });

        jLabel2.setText("FORNECEDOR:");

        jLabel1.setText("DESCRIÇÃO:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescricao))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)))
        );

        tableInfCores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null,  new Integer(0),  new Integer(0), null}
            },
            new String [] {
                "COR", "DESCRIÇÃO DA COR", "ESTOQUE MIN", "ESTOQUE ATUAL", "ALERTA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableInfCores);
        tableInfCores.getColumnModel().getColumn(0).setMinWidth(100);
        tableInfCores.getColumnModel().getColumn(0).setPreferredWidth(100);
        tableInfCores.getColumnModel().getColumn(0).setMaxWidth(100);
        tableInfCores.getColumnModel().getColumn(2).setMinWidth(100);
        tableInfCores.getColumnModel().getColumn(2).setPreferredWidth(100);
        tableInfCores.getColumnModel().getColumn(2).setMaxWidth(100);
        tableInfCores.getColumnModel().getColumn(3).setMinWidth(100);
        tableInfCores.getColumnModel().getColumn(3).setPreferredWidth(100);
        tableInfCores.getColumnModel().getColumn(3).setMaxWidth(100);
        tableInfCores.getColumnModel().getColumn(4).setMinWidth(120);
        tableInfCores.getColumnModel().getColumn(4).setPreferredWidth(120);
        tableInfCores.getColumnModel().getColumn(4).setMaxWidth(120);

        btnRemoverCor.setText("Remover Cor");
        btnRemoverCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverCorActionPerformed(evt);
            }
        });

        btnNovaCor.setText("Nova Cor");
        btnNovaCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaCorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnRemoverCor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNovaCor))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemoverCor)
                    .addComponent(btnNovaCor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelSuperButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSuperButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        createNew();
}//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        edit();
}//GEN-LAST:event_btnEditarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        salvar();
}//GEN-LAST:event_btnSalvarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        search();
}//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        close();
}//GEN-LAST:event_btnSairActionPerformed

    private void btnNovaCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaCorActionPerformed
        StringBuilder builder = validarCor();
        if (builder.toString().isEmpty()) {
            popularGrid(new ItemProduto());
        } else {
            JOptionPane.showMessageDialog(this, builder, MensagensUtil.ATENCAO, 2);
        }

    }//GEN-LAST:event_btnNovaCorActionPerformed

    private void btnRemoverCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverCorActionPerformed
        removeCor();
    }//GEN-LAST:event_btnRemoverCorActionPerformed

    private void jtxtPrecoCustoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPrecoCustoKeyReleased
        MetodosUtil.defineSizeMax(8, jtxtPrecoCusto);
}//GEN-LAST:event_jtxtPrecoCustoKeyReleased

    private void jtxtPrecoVendaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPrecoVendaKeyReleased
        MetodosUtil.defineSizeMax(8, jtxtPrecoVenda);
    }//GEN-LAST:event_jtxtPrecoVendaKeyReleased

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int opcao = JOptionPane.showOptionDialog(rootPane, MensagensUtil.MENSAGEM_CONFIRMAR_EXCLUIR, MensagensUtil.ATENCAO,
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, new String[]{"Sim", "Não"}, "Não");
        if (opcao == JOptionPane.YES_OPTION) {
            deletarProduto();
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtFornecedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFornecedorFocusLost
        jtxtPrecoCusto.requestFocus();
    }//GEN-LAST:event_txtFornecedorFocusLost

    private void txtReferenciaCatalogoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReferenciaCatalogoKeyReleased
        MetodosUtil.defineSizeMax(20, txtReferenciaCatalogo);
    }//GEN-LAST:event_txtReferenciaCatalogoKeyReleased

    private void txtCodigoFornecedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoFornecedorKeyReleased
        MetodosUtil.defineSizeMax(20, txtCodigoFornecedor);
    }//GEN-LAST:event_txtCodigoFornecedorKeyReleased

    private void txtCodigoBarrasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoBarrasKeyReleased
        MetodosUtil.defineSizeMax(20, txtCodigoBarras);
    }//GEN-LAST:event_txtCodigoBarrasKeyReleased

    private void txtCodigoProFiscalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoProFiscalKeyReleased
        MetodosUtil.defineSizeMax(20, txtCodigoProFiscal);
    }//GEN-LAST:event_txtCodigoProFiscalKeyReleased

    private void txtCodigoForFiscalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoForFiscalKeyReleased
        MetodosUtil.defineSizeMax(20, txtCodigoForFiscal);
    }//GEN-LAST:event_txtCodigoForFiscalKeyReleased

    private void txtFornecedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFornecedorKeyReleased
        MetodosUtil.defineSizeMax(150, txtFornecedor);
    }//GEN-LAST:event_txtFornecedorKeyReleased

    private void txtDescricaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescricaoKeyReleased
        MetodosUtil.defineSizeMax(150, txtDescricao);
    }//GEN-LAST:event_txtDescricaoKeyReleased
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovaCor;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnRemoverCor;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField jtxtPrecoCusto;
    private javax.swing.JFormattedTextField jtxtPrecoVenda;
    private javax.swing.JPanel panelSuperButton;
    private javax.swing.JTable tableInfCores;
    private javax.swing.JTextField txtCodigoBarras;
    private javax.swing.JTextField txtCodigoForFiscal;
    private javax.swing.JTextField txtCodigoFornecedor;
    private javax.swing.JTextField txtCodigoProFiscal;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtEstoqueTotal;
    private javax.swing.JTextField txtFornecedor;
    private javax.swing.JTextField txtReferenciaCatalogo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void createNew() {
        produto = null;
        clear();
        disableTela(true);
        popularGrid(new ItemProduto());

        btnSalvar.setEnabled(true);
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);

        //foca campo Descrição
        txtDescricao.requestFocus();
    }

    @Override
    public void edit() {
        disableTela(ControleAcesso.ATIVA_BTN_CADASTRAR_PRODUTO);
        btnSalvar.setEnabled(ControleAcesso.ATIVA_BTN_CADASTRAR_PRODUTO);
        btnEditar.setEnabled(false);
    }

    @Override
    public void search() {
        FormConsultaProduto form = new FormConsultaProduto(true, this);
        form.setVisible(true);
    }

    @Override
    public void print() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public boolean validarTela() {
        StringBuilder stringError = new StringBuilder();
        if (txtDescricao.getText().trim().isEmpty()) {
            stringError.append(MessageProduto.CAMPO_DESCRICAO_OBRIGATORIO);
        }
        if (txtReferenciaCatalogo.getText().trim().isEmpty()) {
            if (!stringError.toString().isEmpty()) {
                stringError.append("\n");
            }
            stringError.append(MessageProduto.CAMPO_REFERENCIA_PRODUTO_OBRIGATORIO);
        }
        if (jtxtPrecoVenda.getText().trim().isEmpty()) {
            if (!stringError.toString().isEmpty()) {
                stringError.append("\n");
            }
            stringError.append(MessageProduto.CAMPO_PRECO_VENDA_OBRIGATORIO);
        }

        //Validando cor
        if (((DefaultTableModel) tableInfCores.getModel()).getRowCount() > 0) {

            StringBuilder stringErroCor = validarCor();
            if (!stringErroCor.toString().isEmpty()) {
                if (!stringError.toString().isEmpty()) {
                    stringError.append("\n");
                }
                stringError.append(stringErroCor);
            }
        } else {
            if (!stringError.toString().isEmpty()) {
                stringError.append("\n");
            }
            stringError.append(MessageProduto.COR_OBRIGATORIO);
        }

        if (!stringError.toString().isEmpty()) {
            JOptionPane.showMessageDialog(this, stringError, MensagensUtil.ATENCAO, 2);
        }

        return stringError.toString().isEmpty();
    }

    @Override
    public void pushToModel() {
        if (produto == null) {
            produto = new Produto();
        }
        if (produto.getFornecedor() == null) {
            produto.setFornecedor(new Fornecedor());
        }
        if (produto.getFornecedor().getPessoa() == null) {
            produto.getFornecedor().setPessoa(new Pessoa());
        }

        if (!txtDescricao.getText().isEmpty()) {
            produto.setDescricao(txtDescricao.getText().trim());
        } else {
            produto.setDescricao(null);
        }

        if (!txtFornecedor.getText().isEmpty()) {
            produto.getFornecedor().getPessoa().setNome(txtFornecedor.getText().trim());
        } else {
            produto.getFornecedor().getPessoa().setNome(null);
        }

        if (!txtReferenciaCatalogo.getText().isEmpty()) {
            produto.setReferenciaCatalogo(txtReferenciaCatalogo.getText().trim());
        } else {
            produto.setReferenciaCatalogo(null);
        }

        if (!txtCodigoFornecedor.getText().isEmpty()) {
            produto.getFornecedor().setCodigo(txtCodigoFornecedor.getText().trim());
        } else {
            produto.getFornecedor().setCodigo(null);
        }

        if (!txtCodigoBarras.getText().isEmpty()) {
            produto.setCodigoBarra(txtCodigoBarras.getText().trim());
        } else {
            produto.setCodigoBarra(null);
        }

        if (!txtCodigoProFiscal.getText().isEmpty()) {
            produto.setCodigoProFiscal(txtCodigoProFiscal.getText().trim());
        } else {
            produto.setCodigoProFiscal(null);
        }

        if (!txtCodigoForFiscal.getText().isEmpty()) {
            produto.setCodigoForFiscal(txtCodigoForFiscal.getText().trim());
        } else {
            produto.setCodigoForFiscal(null);
        }

        if (!txtEstoqueTotal.getText().isEmpty()) {
            produto.setEstoqueTotal(Integer.parseInt(txtEstoqueTotal.getText().trim()));
        } else {
            produto.setEstoqueTotal(-1);
        }

        if (!jtxtPrecoCusto.getText().isEmpty()) {
            produto.setValorCusto(Float.parseFloat(jtxtPrecoCusto.getText().replace(".", "").replace(",", ".")));
        } else {
            produto.setValorCusto(-1);
        }

        if (!jtxtPrecoVenda.getText().isEmpty()) {
            produto.setValorVenda(Float.parseFloat(jtxtPrecoVenda.getText().replace(".", "").replace(",", ".")));
        } else {
            produto.setValorVenda(-1);
        }

        pushToModelCor();
    }

    private ItemProduto returnObjListPositionGrid(List<ItemProduto> list, int position) {

        if (list.isEmpty() || list.size() <= position) {
            return new ItemProduto();
        }

        return list.get(position);
    }

    private void pushToModelCor() {

        //Para a edição na tabela
        tableInfCores.getDefaultEditor(String.class).stopCellEditing();
//        tableInfCores.getDefaultEditor(Integer.class).stopCellEditing();

        if (produto == null) {
            produto = new Produto();
        }

        DefaultTableModel dtm = (DefaultTableModel) tableInfCores.getModel();
        int x = dtm.getRowCount();
        for (int i = 0; i < x; i++) {
            ItemProduto itemProduto = returnObjListPositionGrid(produto.getListaItensProduto(), i);
            if (itemProduto.getCor() == null) {
                itemProduto.setCor(new Cor());
            }
            if (dtm.getValueAt(i, 0) != null) {
                itemProduto.getCor().setCodigo(dtm.getValueAt(i, 0).toString());
            } else {
                itemProduto.getCor().setCodigo(null);
            }

            if (dtm.getValueAt(i, 1) != null) {
                itemProduto.getCor().setDescricao(dtm.getValueAt(i, 1).toString());
            } else {
                itemProduto.getCor().setDescricao(null);
            }

            itemProduto.setEstoqueMinimo(Integer.parseInt(dtm.getValueAt(i, 2).toString()));
            itemProduto.setEstoqueAtual(Integer.parseInt(dtm.getValueAt(i, 3).toString()));
            if (produto.getListaItensProduto().contains(itemProduto)) {
                produto.getListaItensProduto().remove(itemProduto);
                produto.getListaItensProduto().add(i, itemProduto);
            } else {
                produto.getListaItensProduto().add(itemProduto);
            }
        }
    }

    @Override
    public void popularTela() {
        txtDescricao.setText(produto.getDescricao());
        if (produto.getFornecedor() != null) {
            txtFornecedor.setText(produto.getFornecedor().getPessoa().getNome());
            txtCodigoFornecedor.setText(produto.getFornecedor().getCodigo());
        }
        txtReferenciaCatalogo.setText(produto.getReferenciaCatalogo());
        txtCodigoBarras.setText(produto.getCodigoBarra());
        txtCodigoProFiscal.setText(produto.getCodigoProFiscal());
        txtCodigoForFiscal.setText(produto.getCodigoForFiscal());

        jtxtPrecoCusto.setText(MetodosUtil.formatarValorDinheiro(produto.getValorCusto()));
        jtxtPrecoVenda.setText(MetodosUtil.formatarValorDinheiro(produto.getValorVenda()));

        limparGrid();
        for (ItemProduto itemProduto : produto.getListaItensProduto()) {
            popularGrid(itemProduto);
        }

        txtEstoqueTotal.setText(calcEstoqueTotal() + "");
    }

    @Override
    public void salvar() {
        try {
            if (validarTela()) {
                pushToModel();
                mantemProduto(produto);
            }
        } catch (Exception ex) {
            LogUtil.logDescricaoErro(this.getClass(), ex);
            JOptionPane.showMessageDialog(this, MessageProduto.ERRO_SALVAR_PRODUTO, MensagensUtil.ERRO, 0);
        }
    }

    public void salvarComSucesso() {
        JOptionPane.showMessageDialog(this, MensagensUtil.MENSAGEM_SUCESSO_CADASTRO, MensagensUtil.SUCESSO, 1);
        disableTela(false);
        btnSalvar.setEnabled(false);
        btnEditar.setEnabled(true);
        btnExcluir.setEnabled(ControleAcesso.ATIVA_BTN_DELETAR_PRODUTO);
    }

    @Override
    public void close() {
        if (!btnSalvar.isEnabled()) {
            fecharForm();
        } else {
            int opcao = JOptionPane.showOptionDialog(rootPane, MensagensUtil.MENSAGEM_CONFIRMAR_SAIR, MensagensUtil.ATENCAO,
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE, null, new String[]{"Sim", "Não"}, "Não");
            if (opcao == JOptionPane.YES_OPTION) {
                fecharForm();
            }
        }
    }

    private void fecharForm() {
        createNew();
        this.dispose();
    }

    @Override
    public void initialize() {

        createNew();

        //evento de inserção de tados na grid de cor
        tableInfCores.getModel().addTableModelListener(new TableModelListener() {

            @Override
            public void tableChanged(TableModelEvent e) {

                DefaultTableModel dtm = (DefaultTableModel) tableInfCores.getModel();
                if (tableInfCores.getSelectedRow() >= 0) {
                    if (dtm.getRowCount() > 1) {
                        for (int linha = 0; linha < dtm.getRowCount(); linha++) {
                            if (dtm.getValueAt(linha, 0) != null) {
                                if ((dtm.getValueAt(linha, 0).equals(dtm.getValueAt(tableInfCores.getSelectedRow(), 0)))
                                        && (linha != tableInfCores.getSelectedRow())) {

                                    dtm.setValueAt(null, tableInfCores.getSelectedRow(), 0);
                                    selectTableCell(tableInfCores.getSelectedRow(), 0);
                                    JOptionPane.showMessageDialog(null, MessageProduto.CODIGO_COR_REPETIDO, MensagensUtil.ATENCAO, 2);
                                    return;
                                }
                            }
                        }
                    }

                    if (e.getColumn() == 2 || e.getColumn() == 3) {
                        int row = tableInfCores.getSelectedRow();
                        if ((Integer) dtm.getValueAt(row, 3) <= (Integer) dtm.getValueAt(row, 2)
                                && (Integer) dtm.getValueAt(row, 3) != 0
                                && (Integer) dtm.getValueAt(row, 2) != 0) {

                            dtm.setValueAt(MessageProduto.ESTOQUE_BAIXO, row, 4);

                        } else {
                            dtm.setValueAt("", row, 4);
                        }
                    }
                }


                //incrementa total de produtos     
                int countTotal = 0;
                for (int i = 0; i < dtm.getRowCount(); i++) {

                    countTotal += ((Integer) dtm.getValueAt(i, 3)).intValue();

                }

                txtEstoqueTotal.setText(countTotal + "");
            }
        });

        //pular de campo com enter
        MetodosUtil.enterPularCampos(this);
        //define letras maiusculas
        MetodosUtil.letrasMaiusculas(this.getContentPane());

        //Logica para fechar tela pela botao do frame
        addListenerParaExibirMgsFecharTela();

        //Inicializa Acesso
        this.inicializaAcessoPorPerfil();
    }

    @Override
    public void showFrame() {
        setLocationRelativeTo(null);
        disableTela(false);
        setExtendedState(NORMAL);
        initialize();
        this.setVisible(true);
    }

    private void selectTableCell(int row, int col) {
        tableInfCores.setRowSelectionInterval(row, row);
        tableInfCores.setColumnSelectionInterval(col, col);
    }

    @Override
    public void clear() {
        txtDescricao.setText(null);
        txtFornecedor.setText(null);
        txtReferenciaCatalogo.setText(null);
        txtCodigoFornecedor.setText(null);
        txtCodigoBarras.setText(null);
        txtCodigoProFiscal.setText(null);
        txtCodigoForFiscal.setText(null);
        txtEstoqueTotal.setText(null);
        jtxtPrecoCusto.setText(null);
        jtxtPrecoVenda.setText(null);

        limparGrid();
    }

    /**
     * limpa os dados da grid
     */
    private void limparGrid() {
        DefaultTableModel dtm = (DefaultTableModel) tableInfCores.getModel();
        int x = dtm.getRowCount();
        for (int a = 0; a < x; a++) {
            dtm.removeRow(0);
        }
    }

    @Override
    public void inicializaAcessoPorPerfil() {
//        this.btnEditar.setEnabled(ControleAcesso.ATIVA_BTN_CADASTRAR_PRODUTO);
        if (!ControleAcesso.ATIVA_BTN_CADASTRAR_PRODUTO) {
            disableTela(false);
        }
        this.btnNovo.setEnabled(ControleAcesso.ATIVA_BTN_CADASTRAR_PRODUTO);
        this.btnSalvar.setEnabled(ControleAcesso.ATIVA_BTN_CADASTRAR_PRODUTO);
        this.btnExcluir.setEnabled(false);
        this.btnPesquisar.setEnabled(ControleAcesso.ATIVA_BTN_CONSULTAR_PRODUTO);
    }

    

    /**
     * **************************
     * GRID COR PRODUTO *INICIO*
     **************************
     */
    public class MyComboBoxRenderer extends JComboBox implements TableCellRenderer {

        public MyComboBoxRenderer(String[] items) {
            super(items);
        }

        public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {
            if (isSelected) {
                setForeground(table.getSelectionForeground());
                super.setBackground(table.getSelectionBackground());
            } else {
                setForeground(table.getForeground());
                setBackground(table.getBackground());
            }

            // Select the current value  
            setSelectedItem(value);
            return this;
        }
    }

    public class MyComboBoxEditor extends DefaultCellEditor {

        public MyComboBoxEditor(String[] items) {
            super(new JComboBox(items));
        }
    }

    /**
     * popula a grid
     *
     * @param aux
     */
    private void popularGrid(ItemProduto aux) {
        if (aux.getCor() == null) {
            aux.setCor(new Cor());
        }

        DefaultTableModel dtm = (DefaultTableModel) tableInfCores.getModel();

        String alerta = null;
        if (aux.getEstoqueAtual() <= aux.getEstoqueMinimo()
                && aux.getEstoqueAtual() != 0
                && aux.getEstoqueMinimo() != 0) {
            alerta = MessageProduto.ESTOQUE_BAIXO;
        }

        dtm.addRow(new Object[]{
                    aux.getCor().getCodigo(),
                    aux.getCor().getDescricao(),
                    aux.getEstoqueMinimo(),
                    aux.getEstoqueAtual(),
                    alerta
                });
                
    }

    private StringBuilder validarCor() {
        DefaultTableModel dtm = (DefaultTableModel) tableInfCores.getModel();
        if (dtm.getRowCount() == 0) {
            return new StringBuilder();
        }

        int indexUltimaCor = dtm.getRowCount() - 1;

        StringBuilder stringError = new StringBuilder();
        if (dtm.getValueAt(indexUltimaCor, 0) == null || dtm.getValueAt(indexUltimaCor, 0).toString().isEmpty()) {
            stringError.append(MessageProduto.COLUNA_COR_OBRIGATORIO);
        }

        if (dtm.getValueAt(indexUltimaCor, 1) == null || dtm.getValueAt(indexUltimaCor, 1).toString().isEmpty()) {
            if (!stringError.toString().isEmpty()) {
                stringError.append("\n");
            }
            stringError.append(MessageProduto.COLUNA_DESCRICAO_COR_OBRIGATORIO);
        }

        return stringError;
    }

    /**
     * **************************
     * GRID COR PRODUTO *FIM*
     **************************
     */
    /**
     * habilita/desabilita todos os campos dá tela
     */
    private void disableTela(boolean value) {
        txtDescricao.setEnabled(value);
        txtFornecedor.setEnabled(value);
        txtReferenciaCatalogo.setEnabled(value);
        txtCodigoFornecedor.setEnabled(value);
        txtCodigoBarras.setEnabled(value);
        txtCodigoProFiscal.setEnabled(value);
        txtCodigoForFiscal.setEnabled(value);
        jtxtPrecoCusto.setEnabled(value);
        jtxtPrecoVenda.setEnabled(value);

        btnRemoverCor.setEnabled(value);
        btnNovaCor.setEnabled(value);
        tableInfCores.setEnabled(value);
    }

    /**
     * Metodo execultado para enviar os dados para o server e realizar o
     * cadastro
     *
     * @param produto
     * @param informacoesComplementares
     */
    private void mantemProduto(Produto produto) {
        SwingWorkerProduto<Produto> workProduto = new SwingWorkerProduto<Produto>();
        workProduto.setProduto(produto);
        workProduto.setFormProduto(this);
        workProduto.workSalvaProduto.execute();
    }

    /**
     * Calcula o total de estoque pelos valores informados na grid de cor
     *
     * @return
     */
    private int calcEstoqueTotal() {
        int totalEstoque = 0;

        DefaultTableModel dtm = (DefaultTableModel) tableInfCores.getModel();
        int x = dtm.getRowCount();
        for (int i = 0; i < x; i++) {
            totalEstoque += (Integer.parseInt(dtm.getValueAt(i, 3).toString()));
        }

        return totalEstoque;
    }

    /**
     * metodo para remover a cor selecionada
     */
    private void removeCor() {
        JTable table = tableInfCores;

        //atualiza lista de cor
        pushToModelCor();
        int row = table.getSelectedRow();

        ItemProduto itemProduto = produto.getListaItensProduto().get(row);

        if (itemProduto.getId() != null) {
            SwingWorkerProduto worker = new SwingWorkerProduto();
            worker.setItemProduto(itemProduto);
            worker.setFormProduto(this);
            worker.workRemoveItemProduto.execute();
        }

    }
    /**
     * remove item Produto na tela ou seja a cor
     * @param itemProduto 
     */
    public void removeItemProdutoNaTela(ItemProduto itemProduto)
    {
        //removendo o item produto do objeto dá tela
        if (produto.getListaItensProduto().contains(itemProduto)) {
            produto.getListaItensProduto().remove(itemProduto);
        }
        
        JTable table = tableInfCores;
        int row = table.getSelectedRow();
        DefaultTableModel dtm = (DefaultTableModel) table.getModel();
        dtm.removeRow(row);
        
        JOptionPane.showMessageDialog(this, MessageProduto.SUCESSO_REMOVER_COR, MensagensUtil.SUCESSO, 1);
    }

    /**
     * metodo para remover produto
     *      
     */
    private void deletarProduto() {

        if (this.produto != null) {
            SwingWorkerProduto worker = new SwingWorkerProduto();
            worker.setFormProduto(this);
            worker.setProduto(this.produto);
            worker.workRemoveProduto.execute();
        }

    }
    
    /**
     * 
     */
    public void removeProdutoComSucesso() {
        JOptionPane.showMessageDialog(this, MessageProduto.SUCESSO_REMOVER_PRODUTO, MensagensUtil.SUCESSO, 1);
        createNew();
    }

    /**
     * Logica para quando o usuario clicar no botao fechar do frame exibir a
     * tela de confirmação
     */
    private void addListenerParaExibirMgsFecharTela() {
        //cancela acao do botao fechar
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

        //add windowsListener sobrescrevendo o metodo windowClosing
        addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                if (e.getID() == WindowEvent.WINDOW_CLOSING) {
                    close();
                }
            }
        });
    }
}
