/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormProspeccoes.java
 *
 * Created on 26/03/2012, 22:08:40
 */
package br.com.dcoracoes.client.telas.prospeccoes;

import br.com.dcoracoes.client.App;
import br.com.dcoracoes.client.ControleAcesso;
import br.com.dcoracoes.client.classes.serverimpl.AlertaServerImpl;
import br.com.dcoracoes.client.enuns.Enum_Situacao_Alerta;
import br.com.dcoracoes.client.interfaces.InterfaceCadastroCompleto;
import br.com.dcoracoes.client.swingworker.SwingWorkerProspeccoes;
import br.com.dcoracoes.client.telas.principal.FormPrincipal;
import br.com.dcoracoes.client.telas.venda.FormVenda;
import br.com.dcoracoes.client.util.LogUtil;
import br.com.dcoracoes.client.util.MensagensUtil;
import br.com.dcoracoes.client.util.MetodosUtil;
import br.com.dcoracoes.client.util.message.MessageProspeccao;
import br.com.dcoracoes.servico.service.Alerta;
import br.com.dcoracoes.servico.service.Pessoa;
import br.com.dcoracoes.servico.service.Revendedor;
import br.com.wedesenv.common.date.DateUtil;
import java.awt.event.InputEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cleberson
 */
public class FormProspeccoes extends javax.swing.JDialog implements InterfaceCadastroCompleto {

    //atributos
    private Alerta prospeccao;
    private Alerta prospeccaoSearch;
    private Date dateCriacaoAlerta;
    private List<Alerta> listAlertaGrid;
    private Revendedor revendedor = null;
    private JFrame formChamada;

    public Alerta getProspeccao() {
        return prospeccao;
    }

    public void setProspeccao(Alerta prospeccao) {
        this.prospeccao = prospeccao;
        
        //buscar as prospeccoes e popular na tela
        if (prospeccaoSearch == null) {
            if (listAlertaGrid == null) {
                listAlertaGrid = new ArrayList<Alerta>();
            }
            listAlertaGrid.add(prospeccao);
            limparGrid();

            popularGridProspeccoes(prospeccao);
        } else {
            consultarProspeccoes(prospeccaoSearch, false);
        }
    }
    
    public Revendedor getRevendedor() {
        return revendedor;
    }

    public void setRevendedor(Revendedor revendedor) {
        this.revendedor = revendedor;
        txtRevendedor.setText(this.revendedor.getPessoa().getNome());
    }

    /** Creates new form FormProspeccoes
     * @param revendedor
     * @param modal
     * @param formChamada - passar null quando não chamada da tela principal
     */
    public FormProspeccoes(Revendedor revendedor, boolean modal, JFrame formChamada) {
        initComponents();
        setLocationRelativeTo(null);
        setModal(modal);
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage("src/main/resources/imagens/outras/icon_SGC.gif"));
        disablePanelProspeccoes(false);
        this.formChamada = formChamada;

        this.initialize();
        
        if (revendedor != null) {
            buscarProspeccaoRevendedor(revendedor);
        } else {
            createNew();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSuperButton = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtData = new javax.swing.JFormattedTextField();
        jtxtHora = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        cbSituacao = new javax.swing.JComboBox();
        txtAtendente = new javax.swing.JTextField();
        txtRevendedor = new javax.swing.JTextField();
        txtProtocolo = new javax.swing.JTextField();
        txtAssunto = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaDescricao = new javax.swing.JTextArea();
        btnBuscarRevendedor = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableProspeccoes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Prospecções");

        panelSuperButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(43, 115, 186)));
        panelSuperButton.setPreferredSize(new java.awt.Dimension(885, 67));

        btnNovo.setFont(new java.awt.Font("Tahoma", 1, 14));
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/32x32/document-new.png"))); // NOI18N
        btnNovo.setText("NOVO");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Tahoma", 1, 14));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/32x32/img_edit_32x32.png"))); // NOI18N
        btnEditar.setText("EDITAR");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 14));
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/32x32/img_salvar_32x32.png"))); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnPesquisar.setFont(new java.awt.Font("Tahoma", 1, 14));
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/32x32/system-search.png"))); // NOI18N
        btnPesquisar.setText("PESQUISAR");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnSair.setFont(new java.awt.Font("Tahoma", 1, 14));
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/32x32/sair32x32.png"))); // NOI18N
        btnSair.setText("SAIR");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(40, 60));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        jPanel7.setPreferredSize(new java.awt.Dimension(30, 41));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        jPanel8.setPreferredSize(new java.awt.Dimension(30, 41));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        jPanel9.setPreferredSize(new java.awt.Dimension(30, 41));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelSuperButtonLayout = new javax.swing.GroupLayout(panelSuperButton);
        panelSuperButton.setLayout(panelSuperButtonLayout);
        panelSuperButtonLayout.setHorizontalGroup(
            panelSuperButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelSuperButtonLayout.setVerticalGroup(
            panelSuperButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSuperButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(btnSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovo))
                .addContainerGap())
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(43, 115, 186)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setForeground(new java.awt.Color(43, 115, 186));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PROSPECÇÕES");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 916, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DATA");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("HORA");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ATENDENTE");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("REVENDEDOR(A)");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("PROTOCOLO");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ASSUNTO");

        jtxtData.setEditable(false);
        jtxtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        jtxtData.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtxtHora.setEditable(false);
        jtxtHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        jtxtHora.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("SITUAÇÃO");

        cbSituacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "selecione...", "Resolvida", "Em Aberto" }));

        txtAtendente.setEditable(false);
        txtAtendente.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtRevendedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRevendedorKeyReleased(evt);
            }
        });

        txtProtocolo.setEditable(false);
        txtProtocolo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtProtocolo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtProtocoloFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel4.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel5.setPreferredSize(new java.awt.Dimension(10, 40));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        txtAreaDescricao.setColumns(20);
        txtAreaDescricao.setRows(5);
        jScrollPane1.setViewportView(txtAreaDescricao);

        btnBuscarRevendedor.setText("...");
        btnBuscarRevendedor.setToolTipText("Buscar Revendedor");
        btnBuscarRevendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarRevendedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(jtxtData, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                        .addGap(4, 4, 4)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(jtxtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRevendedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarRevendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(txtProtocolo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(txtAssunto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 813, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbSituacao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProtocolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel11Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel11Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtxtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel11Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtxtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtRevendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnBuscarRevendedor, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)))
                                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        tableProspeccoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Protocolo", "Atendente", "Revendedor", "Assunto", "Situação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableProspeccoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProspeccoesMouseClicked(evt);
            }
        });
        tableProspeccoes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableProspeccoesKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tableProspeccoes);
        tableProspeccoes.getColumnModel().getColumn(0).setMinWidth(100);
        tableProspeccoes.getColumnModel().getColumn(0).setPreferredWidth(100);
        tableProspeccoes.getColumnModel().getColumn(0).setMaxWidth(100);
        tableProspeccoes.getColumnModel().getColumn(1).setMinWidth(200);
        tableProspeccoes.getColumnModel().getColumn(1).setPreferredWidth(200);
        tableProspeccoes.getColumnModel().getColumn(1).setMaxWidth(200);
        tableProspeccoes.getColumnModel().getColumn(3).setMinWidth(200);
        tableProspeccoes.getColumnModel().getColumn(3).setPreferredWidth(200);
        tableProspeccoes.getColumnModel().getColumn(3).setMaxWidth(200);
        tableProspeccoes.getColumnModel().getColumn(4).setMinWidth(100);
        tableProspeccoes.getColumnModel().getColumn(4).setPreferredWidth(100);
        tableProspeccoes.getColumnModel().getColumn(4).setMaxWidth(100);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 940, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSuperButton, javax.swing.GroupLayout.Alignment.LEADING, 0, 940, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSuperButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        createNew();
}//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        edit();
}//GEN-LAST:event_btnEditarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        salvar();
}//GEN-LAST:event_btnSalvarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        search();
}//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        close();
}//GEN-LAST:event_btnSairActionPerformed

    private void tableProspeccoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProspeccoesMouseClicked
        // TODO add your handling code here:
        selectGrid(evt);
    }//GEN-LAST:event_tableProspeccoesMouseClicked

    private void tableProspeccoesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableProspeccoesKeyReleased
        // TODO add your handling code here:
        selectGrid(evt);
    }//GEN-LAST:event_tableProspeccoesKeyReleased

    private void btnBuscarRevendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarRevendedorActionPerformed
        // TODO add your handling code here:
        searchRevendedor();
    }//GEN-LAST:event_btnBuscarRevendedorActionPerformed

    private void txtProtocoloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtProtocoloFocusGained
        // TODO add your handling code here:
        txtAssunto.requestFocus();
    }//GEN-LAST:event_txtProtocoloFocusGained

    private void txtRevendedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRevendedorKeyReleased
        // TODO add your handling code here:
        if (this.revendedor != null) {
            this.revendedor = null;
            txtRevendedor.setText(null);
        }
    }//GEN-LAST:event_txtRevendedorKeyReleased

    /**
     * metodo para selecionar o campo dá grid
     * @param evt 
     */
    private void selectGrid(InputEvent evt) {
        disablePanelProspeccoes(false);
        btnEditar.setEnabled(true);
        btnSalvar.setEnabled(false);
        int row = ((JTable) evt.getSource()).getSelectedRow();

        prospeccao = listAlertaGrid.get(row);
        populaCampoEditar(prospeccao);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarRevendedor;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cbSituacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JFormattedTextField jtxtData;
    private javax.swing.JFormattedTextField jtxtHora;
    private javax.swing.JPanel panelSuperButton;
    private javax.swing.JTable tableProspeccoes;
    private javax.swing.JTextArea txtAreaDescricao;
    private javax.swing.JTextField txtAssunto;
    private javax.swing.JTextField txtAtendente;
    private javax.swing.JTextField txtProtocolo;
    private javax.swing.JTextField txtRevendedor;
    // End of variables declaration//GEN-END:variables

    @Override
    public void createNew() {
        limparCampos();
        disablePanelProspeccoes(true);
        prospeccao = null;
        prospeccaoSearch = null;

        dateCriacaoAlerta = new Date(System.currentTimeMillis());
        jtxtData.setValue(dateCriacaoAlerta);
        jtxtHora.setValue(dateCriacaoAlerta);

        txtAtendente.setText(buscarAtendente());
        txtProtocolo.setText(geraProtocolo());

        btnEditar.setEnabled(false);
        btnSalvar.setEnabled(true);

        //foco no campo consultor(a)
        txtRevendedor.requestFocus();
    }

    @Override
    public void edit() {
        disablePanelProspeccoes(ControleAcesso.ATIVA_BTN_CADASTRAR_PROSPECCAO);
        btnEditar.setEnabled(false);
        btnSalvar.setEnabled(ControleAcesso.ATIVA_BTN_CADASTRAR_PROSPECCAO);
    }

    @Override
    public void search() {
        FormFiltroConsultaProspeccoes filtro = new FormFiltroConsultaProspeccoes(this);
        filtro.setVisible(true);
    }

    @Override
    public void print() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public boolean validarTela() {
        StringBuilder stringError = new StringBuilder();
        if (txtRevendedor.getText().trim().isEmpty()) {
            stringError.append(MessageProspeccao.CAMPO_CONSULTOR_OBRIGATORIO);
        }
        if (txtAssunto.getText().trim().isEmpty()) {
            if (!stringError.toString().isEmpty()) {
                stringError.append("\n");
            }
            stringError.append(MessageProspeccao.CAMPO_ASSUNTO_OBRIGATORIO);
        }
        if (cbSituacao.getSelectedIndex() == 0) {
            if (!stringError.toString().isEmpty()) {
                stringError.append("\n");
            }
            stringError.append(MessageProspeccao.CAMPO_SITUACAO_OBRIGATORIO);
        }

        if (!stringError.toString().isEmpty()) {
            JOptionPane.showMessageDialog(this, stringError, MensagensUtil.ATENCAO, 2);
        }

        return stringError.toString().isEmpty();
    }

    @Override
    public void pushToModel() {
        if (prospeccao == null) {
            prospeccao = new Alerta();
        }

        prospeccao.setDataAlerta(DateUtil.dateAsXMLGregorianCalendar(dateCriacaoAlerta));

        prospeccao.setAtendente(App.getUserLog());

        if (revendedor == null) {
            if (prospeccao.getPessoa() == null) {
                prospeccao.setPessoa(new Pessoa());
            }
            prospeccao.getPessoa().setNome(txtRevendedor.getText().trim());
        } else {
            prospeccao.setPessoa(revendedor.getPessoa());
        }

        prospeccao.setProtocolo(txtProtocolo.getText().trim());

        prospeccao.setAssunto(txtAssunto.getText().trim());

        prospeccao.setDescricao(txtAreaDescricao.getText().trim());

        if (!cbSituacao.getSelectedItem().toString().contains(MessageProspeccao.OPCAO_SELECIONE)) {
            prospeccao.setSituacaoAlerta(recValorSituacao(cbSituacao.getSelectedItem().toString()));
        }

    }

    @Override
    public void popularTela() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void salvar() {
        try {

            if (validarTela()) {
                pushToModel();
                mantemProspeccoes(prospeccao);
            }

        } catch (Exception ex) {
            LogUtil.logDescricaoErro(this.getClass(), ex);
            JOptionPane.showMessageDialog(this, MessageProspeccao.ERRO_SALVAR_PROSPECCAO, MensagensUtil.ERRO, 0);
        }
    }
    
    public void salvarComSucesso() {
        JOptionPane.showMessageDialog(rootPane, MensagensUtil.MENSAGEM_SUCESSO_CADASTRO, MensagensUtil.SUCESSO, 1);
        clear();
    }

    @Override
    public void close() {
        if (!btnSalvar.isEnabled()) {
            closeForm();
        } else {
            int opcao = JOptionPane.showOptionDialog(rootPane, MensagensUtil.MENSAGEM_CONFIRMAR_SAIR, MensagensUtil.ATENCAO,  
                JOptionPane.YES_NO_OPTION,  
                JOptionPane.QUESTION_MESSAGE, null, new String[]{"Sim", "Não"}, "Não"); 
            if (opcao == JOptionPane.YES_OPTION) {
                closeForm();
            }
        }
    }
    
    private void closeForm(){
        this.dispose();
        if(formChamada != null)
            if(formChamada.getClass().toString().contains("FormPrincipal"))
                ((FormPrincipal)formChamada).setFormProspeccoes(null);
            else
                if(formChamada.getClass().toString().contains("FormVenda"))
                    ((FormVenda)formChamada).consultarProspeccoes();
        //TODO
//                else
//                    if(formChamada.getClass().toString().contains("FormRevendedor"))
//                        ((FormRevendedor)formChamada).consultarProspeccoes();
    }

    @Override
    public void initialize() {
        //pular de campo com enter
        MetodosUtil.enterPularCampos(this);
        //define letras maiusculas
        MetodosUtil.letrasMaiusculas(this.getContentPane()); 

        //Logica para fechar tela pela botao do frame
        addListenerParaExibirMgsFecharTela();

        //Inicializa Acesso
        this.inicializaAcessoPorPerfil();
    }

    @Override
    public void clear() {
        limparCampos();

        disablePanelProspeccoes(false);

        btnSalvar.setEnabled(false);
        btnEditar.setEnabled(false);
    }

    /**
     * limpa os dados do panel de cadastro de prospeccoes
     */
    private void limparCampos() {
        dateCriacaoAlerta = null;
        jtxtData.setValue(null);
        jtxtHora.setText("");
        txtAtendente.setText("");
        txtRevendedor.setText("");
        txtProtocolo.setText("");
        txtAssunto.setText("");
        txtAreaDescricao.setText("");
        cbSituacao.setSelectedIndex(0);
    }

    /***************************
     * Disable tela *INICIO*
     ***************************/
    private void disablePanelProspeccoes(boolean value) {
        txtRevendedor.setEnabled(value);
        txtAssunto.setEnabled(value);
        txtAreaDescricao.setEnabled(value);
        cbSituacao.setEnabled(value);
        btnBuscarRevendedor.setEnabled(value);
    }

    /***************************
     * Disable tela *FIM*
     ***************************/
    /**
     * busca o atendente logado no sistema
     */
    private String buscarAtendente() {
        return App.getUserLog().getPessoa().getNome();
    }

    /**
     * gera o protocolo para a prospecção
     * @return 
     */
    private String geraProtocolo() {
        String protocolo = null;
        try {
            AlertaServerImpl alertaServerImpl = new AlertaServerImpl();

            protocolo = alertaServerImpl.gerarNumeroProtocolo();
        } catch (Exception ex) {
            LogUtil.logDescricaoErro(this.getClass(), ex);
            Logger.getLogger(FormProspeccoes.class.getName()).log(Level.SEVERE, null, ex);
        }

        return protocolo;
    }

    /**
     * realiza o cadastro dos dados
     */
    private void mantemProspeccoes(Alerta prospeccao) {
        SwingWorkerProspeccoes<Alerta> workUsuario = new SwingWorkerProspeccoes<Alerta>(prospeccao);
        workUsuario.setFormProspeccoes(this);
        workUsuario.workSalvaProspeccao.execute();
    }
    
    /**
     * popula telas
     * @param lstProspeccoes 
     */
    public void populaTela(List<Alerta> lstProspeccoes) {  
        if (lstProspeccoes.size() > 0) {
            popularGrid(lstProspeccoes);
        } else {
            JOptionPane.showMessageDialog(this, MensagensUtil.MENSAGEM_NENHUM_REGISTRO, MensagensUtil.ATENCAO, 1);
        }
    }

    /**
     * populando a grid com a lista de prospeccoes vinda do server
     * @param list 
     */
    private void popularGrid(List<Alerta> list) {
        for (Alerta obj : list) {
            popularGridProspeccoes(obj);
        }
    }

    /**
     * popula a grid de prospccoes
     * @param aux 
     */
    private void popularGridProspeccoes(Alerta aux) {
        DefaultTableModel dtm = (DefaultTableModel) tableProspeccoes.getModel();
        String situacao = recDescricaoSituacao(aux.getSituacaoAlerta());


        dtm.addRow(new Object[]{
                    aux.getProtocolo(),
                    aux.getAtendente().getPessoa().getNome(),
                    aux.getPessoa().getNome(),
                    aux.getAssunto(),
                    situacao
                });
    }

    /**
     * metodo para popular a prospecção para editar os dados
     */
    private void populaCampoEditar(Alerta prospeccao) {
        dateCriacaoAlerta = DateUtil.asDate(prospeccao.getDataAlerta());
        jtxtData.setValue(dateCriacaoAlerta);
        jtxtHora.setValue(dateCriacaoAlerta);
        txtAtendente.setText(prospeccao.getAtendente().getPessoa().getNome());
        txtRevendedor.setText(prospeccao.getPessoa().getNome());
        txtProtocolo.setText(prospeccao.getProtocolo());
        txtAssunto.setText(prospeccao.getAssunto());
        txtAreaDescricao.setText(prospeccao.getDescricao());
        cbSituacao.setSelectedIndex(recIndexValorSituacao(prospeccao.getSituacaoAlerta()));
    }

    public void consultarProspeccoes(Alerta prospeccao, boolean exibeMsg) {
        limparGrid();
        
        SwingWorkerProspeccoes<Alerta> workUsuario = new SwingWorkerProspeccoes<Alerta> (prospeccao);
        workUsuario.setFormProspeccoes(this);
        workUsuario.workRecListaAlertas.execute(); 
        
    }

    /**
     * limpa os dados da grid
     */
    private void limparGrid() {
        DefaultTableModel dtm = (DefaultTableModel) tableProspeccoes.getModel();
        int x = dtm.getRowCount();
        for (int a = 0; a < x; a++) {
            dtm.removeRow(0);
        }
    }

    /**
     * retorna o valor da situacao selecionado no combo
     * @param situacao
     * @return 
     */
    public int recValorSituacao(String situacao) {
        if (situacao.equalsIgnoreCase(MessageProspeccao.OPCAO_RESOLVIDA)) {
            return Enum_Situacao_Alerta.RESOLVIDO.getCodigo();
        } else {
            return Enum_Situacao_Alerta.EMABERTO.getCodigo();
        }
    }

    /**
     * retorna o valor da situacao selecionado no combo
     * @param situacao
     * @return 
     */
    private int recIndexValorSituacao(int situacao) {
        if (situacao == Enum_Situacao_Alerta.RESOLVIDO.getCodigo()) {
            return 1;
        } else {
            return 2;
        }
    }

    /**
     * retorna a descricao da situacao
     * @param situacao
     * @return 
     */
    private String recDescricaoSituacao(int situacao) {
        if (situacao == 51) {
            return MessageProspeccao.OPCAO_RESOLVIDA;
        } else {
            return MessageProspeccao.OPCAO_EM_ABERTO;
        }
    }

    /**
     * busca as propecções relacionada ao revendedor passado
     * @param revendedor 
     */
    private void buscarProspeccaoRevendedor(Revendedor revendedor) {
        Alerta prospeccao = new Alerta();
        prospeccao.setPessoa(revendedor.getPessoa());

        consultarProspeccoes(prospeccao, false);
    }

    private void searchRevendedor() {
        //TODO
//        FormConsultaRevendedor form = new FormConsultaRevendedor(true, this);
//        form.setVisible(true);
    }

    /**
     * Logica para quando o usuario clicar no botao fechar do frame
     * exibir a tela de confirmação
     */
    private void addListenerParaExibirMgsFecharTela() {
        //cancela acao do botao fechar
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

        //add windowsListener sobrescrevendo o metodo windowClosing
        addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                if (e.getID() == WindowEvent.WINDOW_CLOSING) {
                    close();
                }
            }
        });
    }

    @Override
    public void inicializaAcessoPorPerfil() {
        //this.btnEditar.setEnabled(ControleAcesso.ATIVA_BTN_CADASTRAR_PROSPECCAO);
        if(!ControleAcesso.ATIVA_BTN_CADASTRAR_PROSPECCAO)
            disablePanelProspeccoes(false);
        this.btnNovo.setEnabled(ControleAcesso.ATIVA_BTN_CADASTRAR_PROSPECCAO);
        this.btnSalvar.setEnabled(false);
        this.btnPesquisar.setEnabled(ControleAcesso.ATIVA_BTN_CONSULTAR_PROSPECCAO);
    }

    @Override
    public void showFrame() {
        throw new UnsupportedOperationException("Not supported yet.");
    }
}
