--------------------------------------------------------
--  Arquivo criado - Quinta-feira-Junho-18-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table IF_CANCEL_NFE
--------------------------------------------------------

  CREATE TABLE "HR"."IF_CANCEL_NFE" 
   (	"SEQ_NFE" NUMBER, 
	"EV_INFEV_ID" VARCHAR2(100 BYTE), 
	"EV_INFEV_CORGAO" VARCHAR2(10 BYTE), 
	"EV_INFEV_TPAMB" VARCHAR2(10 BYTE), 
	"EV_INFEV_CNPJ" VARCHAR2(20 BYTE), 
	"EV_INFEV_CHNFE" VARCHAR2(100 BYTE), 
	"EV_INFEV_DHEV" VARCHAR2(50 BYTE), 
	"EV_INFEV_TPEV" VARCHAR2(20 BYTE), 
	"EV_INFEV_NSEQEV" VARCHAR2(20 BYTE), 
	"EV_INFEV_VEREV" VARCHAR2(20 BYTE), 
	"EV_INFEV_DETEV_DESC_EV" VARCHAR2(20 BYTE), 
	"EV_INFEV_DETEV_DESC_NPROT" VARCHAR2(20 BYTE), 
	"EV_INFEV_DETEV_DESC_XJUST" VARCHAR2(200 BYTE), 
	"RET_EV_INFEV_TPAMB" VARCHAR2(20 BYTE), 
	"RET_EV_INFEV_VERAPLIC" VARCHAR2(20 BYTE), 
	"RET_EV_INFEV_CORGAO" VARCHAR2(20 BYTE), 
	"RET_EV_INFEV_CSTAT" VARCHAR2(20 BYTE), 
	"RET_EV_INFEV_XMOTIVO" VARCHAR2(200 BYTE), 
	"RET_EV_INFEV_CHNFE" VARCHAR2(100 BYTE), 
	"RET_EV_INFEV_TPEV" VARCHAR2(10 BYTE), 
	"RET_EV_INFEV_NSQEEV" VARCHAR2(10 BYTE), 
	"RET_EV_INFEV_CNPJDEST" VARCHAR2(20 BYTE), 
	"RET_EV_INFEV_DHREGEV" VARCHAR2(50 BYTE), 
	"RET_EV_INFEV_NPROT" VARCHAR2(100 BYTE), 
	"SIG_URI" VARCHAR2(200 BYTE), 
	"SIG_VALUE" VARCHAR2(2000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IF_CANCEL_NFE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."IF_CANCEL_NFE_PK" ON "HR"."IF_CANCEL_NFE" ("SEQ_NFE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table IF_CANCEL_NFE
--------------------------------------------------------

  ALTER TABLE "HR"."IF_CANCEL_NFE" ADD CONSTRAINT "IF_CANCEL_NFE_PK" PRIMARY KEY ("SEQ_NFE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."IF_CANCEL_NFE" MODIFY ("SEQ_NFE" NOT NULL ENABLE);
