/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CadastroPerfilForm.java
 *
 * Created on 03/05/2012, 22:36:11
 */
package br.com.dcoracoes.client.telas.usuario;

import br.com.dcoracoes.client.ControleAcesso;
import br.com.dcoracoes.client.classes.serverimpl.PerfilServerImpl;
import br.com.dcoracoes.client.classes.serverimpl.UsuarioServerImpl;
import br.com.dcoracoes.client.enuns.Enum_UF;
import br.com.dcoracoes.client.interfaces.InterfaceCadastroCompleto;
import br.com.dcoracoes.client.util.MensagensUtil;
import br.com.dcoracoes.client.util.MetodosUtil;
import br.com.dcoracoes.client.util.componentes.ComboBoxEstado;
import br.com.dcoracoes.client.util.message.MessageUsuario;
import br.com.dcoracoes.client.util.message.OperadorasTelefonicas;
import br.com.dcoracoes.server.enuns.Enum_TipoTelefone;
import br.com.dcoracoes.server.model.cadastro.Email;
import br.com.dcoracoes.server.model.cadastro.Endereco;
import br.com.dcoracoes.server.model.cadastro.Pessoa;
import br.com.dcoracoes.server.model.cadastro.Telefone;
import br.com.dcoracoes.server.model.canalacesso.Perfil;
import br.com.dcoracoes.server.model.canalacesso.Usuario;
import br.com.dcoracoes.transacao.excecao.TransException;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Cleberson
 */
public class FormUsuario extends javax.swing.JFrame implements InterfaceCadastroCompleto {

    private Usuario usuario;
    private List<Perfil> listPerfil;

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
        popularTela();
        
        
        disableTela(false);
        btnEditar.setEnabled(ControleAcesso.ATIVA_BTN_CADASTRAR_USUARIO);
        btnSalvar.setEnabled(false);
    }

    /** Creates new form CadastroUsuarioForm */
    public FormUsuario() {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(NORMAL);
        initialize();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSuperButton = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pswSenha = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        pswConfirmarSenha = new javax.swing.JPasswordField();
        tablePanelDados = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        lblConsultor = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblComplemento = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        lbUF = new javax.swing.JLabel();
        lblCEP = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtComplemento = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        cbUF = new ComboBoxEstado();
        jtxtCEP = new javax.swing.JFormattedTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jtxtTelefoneResidencial = new javax.swing.JFormattedTextField();
        jtxtCelular1 = new javax.swing.JFormattedTextField();
        jtxtTelefoneComercial = new javax.swing.JFormattedTextField();
        jtxtCelular2 = new javax.swing.JFormattedTextField();
        jtxtEmail1 = new javax.swing.JFormattedTextField();
        jtxtEmail2 = new javax.swing.JFormattedTextField();
        cbOperadora1 = new javax.swing.JComboBox();
        cbOperadora2 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        cbPerfil = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Usuário");
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage("src/main/resources/imagens/outras/icon_SGC.gif"));
        setResizable(false);

        panelSuperButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(43, 115, 186)));
        panelSuperButton.setPreferredSize(new java.awt.Dimension(885, 67));

        btnNovo.setFont(new java.awt.Font("Tahoma", 1, 14));
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/32x32/document-new.png"))); // NOI18N
        btnNovo.setText("NOVO");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Tahoma", 1, 14));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/32x32/img_edit_32x32.png"))); // NOI18N
        btnEditar.setText("EDITAR");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 14));
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/32x32/img_salvar_32x32.png"))); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnPesquisar.setFont(new java.awt.Font("Tahoma", 1, 14));
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/32x32/system-search.png"))); // NOI18N
        btnPesquisar.setText("PESQUISAR");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnSair.setFont(new java.awt.Font("Tahoma", 1, 14));
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/32x32/sair32x32.png"))); // NOI18N
        btnSair.setText("SAIR");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(40, 60));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        jPanel7.setPreferredSize(new java.awt.Dimension(30, 41));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        jPanel8.setPreferredSize(new java.awt.Dimension(30, 41));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        jPanel9.setPreferredSize(new java.awt.Dimension(30, 41));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelSuperButtonLayout = new javax.swing.GroupLayout(panelSuperButton);
        panelSuperButton.setLayout(panelSuperButtonLayout);
        panelSuperButtonLayout.setHorizontalGroup(
            panelSuperButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelSuperButtonLayout.setVerticalGroup(
            panelSuperButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSuperButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelSuperButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                        .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                        .addComponent(btnSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNovo)))
                .addContainerGap())
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(43, 115, 186)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setForeground(new java.awt.Color(43, 115, 186));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("USUÁRIO");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setText("LOGIN:");

        txtLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLoginKeyReleased(evt);
            }
        });

        jLabel2.setText("SENHA:");

        pswSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pswSenhaKeyReleased(evt);
            }
        });

        jLabel4.setText("CONFIRMAR SENHA:");

        pswConfirmarSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pswConfirmarSenhaKeyReleased(evt);
            }
        });

        tablePanelDados.setToolTipText("");

        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblConsultor.setText("NOME:");

        lblEndereco.setText("ENDEREÇO:");

        lblNumero.setText("Nº:");

        lblComplemento.setText("COMPLEMENTO:");

        lblCidade.setText("CIDADE:");

        lbUF.setText("UF:");

        lblCEP.setText("CEP:");

        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeKeyReleased(evt);
            }
        });

        txtEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEnderecoKeyReleased(evt);
            }
        });

        txtNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumeroKeyReleased(evt);
            }
        });

        txtComplemento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtComplementoKeyReleased(evt);
            }
        });

        txtCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCidadeKeyReleased(evt);
            }
        });

        try {
            jtxtCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtxtCEP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtCEPKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblConsultor)
                        .addGap(4, 4, 4)
                        .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(lblEndereco)
                                .addGap(4, 4, 4)
                                .addComponent(txtEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(lblCidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCidade, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(lblNumero)
                                .addGap(5, 5, 5)
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(lblComplemento)
                                .addGap(4, 4, 4)
                                .addComponent(txtComplemento, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(lbUF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbUF, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                .addComponent(lblCEP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(81, 81, 81))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblConsultor))
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblEndereco))
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblNumero))
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblComplemento))
                    .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCEP)
                    .addComponent(jtxtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbUF)
                    .addComponent(cbUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCidade)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        tablePanelDados.addTab("Dados Principais", jPanel6);

        jLabel11.setText("TELEFONE RESIDÊNCIAL:");

        jLabel12.setText("CELULAR 1:");

        jLabel13.setText("OPERADORA:");

        jLabel14.setText("TELEFONE COMERCIAL:");

        jLabel15.setText("CELULAR 2:");

        jLabel16.setText("OPERADORA:");

        jLabel17.setText("EMAIL 1:");

        jLabel18.setText("EMAIL 2:");

        jtxtTelefoneComercial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTelefoneComercialActionPerformed(evt);
            }
        });

        jtxtEmail1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtEmail1KeyReleased(evt);
            }
        });

        jtxtEmail2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtEmail2KeyReleased(evt);
            }
        });

        cbOperadora1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "VIVO", "TIM", "CLARO", "OI" }));

        cbOperadora2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "VIVO", "TIM", "CLARO", "OI" }));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtTelefoneResidencial, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtTelefoneComercial, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtCelular1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtCelular2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbOperadora1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbOperadora2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(91, 91, 91))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtEmail2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(263, Short.MAX_VALUE))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel11Layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addComponent(cbOperadora2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbOperadora1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addComponent(jLabel16)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel11Layout.createSequentialGroup()
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(jtxtTelefoneResidencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jtxtTelefoneComercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14)))
                        .addGroup(jPanel11Layout.createSequentialGroup()
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(jtxtCelular1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jtxtCelular2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jtxtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jtxtEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablePanelDados.addTab("Contato", jPanel11);

        jLabel5.setText("PERFIL:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(pswSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel4))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pswConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tablePanelDados, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cbPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pswSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(pswConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tablePanelDados, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSuperButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSuperButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        createNew();
        populaComboPerfil();
}//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        edit();
}//GEN-LAST:event_btnEditarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        salvar();
}//GEN-LAST:event_btnSalvarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        search();
}//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        close();
}//GEN-LAST:event_btnSairActionPerformed

    private void txtLoginKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLoginKeyReleased
        MetodosUtil.defineSizeMax(10, txtLogin);
    }//GEN-LAST:event_txtLoginKeyReleased

    private void txtNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyReleased
        MetodosUtil.defineSizeMax(150, txtNome);
}//GEN-LAST:event_txtNomeKeyReleased

    private void txtEnderecoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEnderecoKeyReleased
        MetodosUtil.defineSizeMax(150, txtEndereco);
}//GEN-LAST:event_txtEnderecoKeyReleased

    private void txtNumeroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroKeyReleased
        MetodosUtil.defineSizeMax(10, txtNumero);
}//GEN-LAST:event_txtNumeroKeyReleased

    private void txtComplementoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtComplementoKeyReleased
        MetodosUtil.defineSizeMax(50, txtComplemento);
}//GEN-LAST:event_txtComplementoKeyReleased

    private void txtCidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCidadeKeyReleased
        MetodosUtil.defineSizeMax(150, txtCidade);
}//GEN-LAST:event_txtCidadeKeyReleased

    private void jtxtTelefoneComercialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTelefoneComercialActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jtxtTelefoneComercialActionPerformed

    private void jtxtEmail1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtEmail1KeyReleased
        MetodosUtil.defineSizeMax(50, jtxtEmail1);
}//GEN-LAST:event_jtxtEmail1KeyReleased

    private void jtxtEmail2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtEmail2KeyReleased
        MetodosUtil.defineSizeMax(50, jtxtEmail2);
}//GEN-LAST:event_jtxtEmail2KeyReleased

    private void pswSenhaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pswSenhaKeyReleased
        MetodosUtil.defineSizeMax(10, pswSenha);
    }//GEN-LAST:event_pswSenhaKeyReleased

    private void pswConfirmarSenhaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pswConfirmarSenhaKeyReleased
        MetodosUtil.defineSizeMax(10, pswConfirmarSenha);
    }//GEN-LAST:event_pswConfirmarSenhaKeyReleased

    private void jtxtCEPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCEPKeyReleased
        MetodosUtil.defineSizeMax(20, jtxtCEP);
}//GEN-LAST:event_jtxtCEPKeyReleased
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cbOperadora1;
    private javax.swing.JComboBox cbOperadora2;
    private javax.swing.JComboBox cbPerfil;
    private javax.swing.JComboBox cbUF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JFormattedTextField jtxtCEP;
    private javax.swing.JFormattedTextField jtxtCelular1;
    private javax.swing.JFormattedTextField jtxtCelular2;
    private javax.swing.JFormattedTextField jtxtEmail1;
    private javax.swing.JFormattedTextField jtxtEmail2;
    private javax.swing.JFormattedTextField jtxtTelefoneComercial;
    private javax.swing.JFormattedTextField jtxtTelefoneResidencial;
    private javax.swing.JLabel lbUF;
    private javax.swing.JLabel lblCEP;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblConsultor;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JPanel panelSuperButton;
    private javax.swing.JPasswordField pswConfirmarSenha;
    private javax.swing.JPasswordField pswSenha;
    private javax.swing.JTabbedPane tablePanelDados;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables

    @Override
    public void createNew() {
        usuario = null;
        clear();
        disableTela(true);
        btnEditar.setEnabled(false);
        btnSalvar.setEnabled(true);
        txtLogin.requestFocus();
    }

    @Override
    public void edit() {
        disableTela(ControleAcesso.ATIVA_BTN_CADASTRAR_USUARIO);
        btnEditar.setEnabled(false);
        btnSalvar.setEnabled(ControleAcesso.ATIVA_BTN_CADASTRAR_USUARIO);
    }

    @Override
    public void search() {
        FormConsultaUsuario form = new FormConsultaUsuario(true, this);
        form.setVisible(true);
    }

    @Override
    public void print() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public boolean validarTela() {
        StringBuilder stringError = new StringBuilder();
        if (txtLogin.getText().trim().isEmpty()) {
            stringError.append(MessageUsuario.CAMPO_LOGIN_OBRIGATORIO);
        }
        if (pswSenha.getText().trim().isEmpty()) {
            if (!stringError.toString().isEmpty()) {
                stringError.append("\n");
            }
            stringError.append(MessageUsuario.CAMPO_SENHA_OBRIGATORIO);
        }
        if (pswConfirmarSenha.getText().trim().isEmpty()) {
            if (!stringError.toString().isEmpty()) {
                stringError.append("\n");
            }
            stringError.append(MessageUsuario.CAMPO_CONFIRMAR_SENHA_OBRIGATORIO);
        }
        if (cbPerfil.getSelectedIndex() == 0) {
            if (!stringError.toString().isEmpty()) {
                stringError.append("\n");
            }
            stringError.append(MessageUsuario.CAMPO_PERFIL_OBRIGATORIO);
        }
        if (txtNome.getText().trim().isEmpty()) {
            if (!stringError.toString().isEmpty()) {
                stringError.append("\n");
            }
            stringError.append(MessageUsuario.CAMPO_NOME_OBRIGATORIO);
        }

        //validando senhas
        if (!pswSenha.getText().trim().isEmpty()) {
            if (!pswConfirmarSenha.getText().trim().isEmpty()) {
                if (!pswSenha.getText().trim().equals(pswConfirmarSenha.getText().trim())) {
                    if (!stringError.toString().isEmpty()) {
                        stringError.append("\n");
                    }
                    stringError.append(MessageUsuario.SENHAS_DIFERENTES);
                }
            }
        }

        if (!stringError.toString().isEmpty()) {
            JOptionPane.showMessageDialog(this, stringError, MensagensUtil.ATENCAO, 2);
        }

        return stringError.toString().isEmpty();

    }

    @Override
    public void pushToModel() {
        if (usuario == null) {
            usuario = new Usuario();
        }
        if (usuario.getPessoa() == null) {
            usuario.setPessoa(new Pessoa());
        }

        usuario.setLogin(txtLogin.getText().trim());
        usuario.setSenha(pswSenha.getText().trim());
        usuario.setPerfil(listPerfil.get(cbPerfil.getSelectedIndex() - 1));

        pushToModelDadosPrincipais();
        pushToModelContato();
    }

    @Override
    public void popularTela() {

        clear();

        txtLogin.setText(usuario.getLogin());
        pswSenha.setText(usuario.getSenha());
//        pswConfirmarSenha.setText(usuario.getSenha());
        cbPerfil.setSelectedItem(usuario.getPerfil().getNomePerfil());

        popularDadosPrincipais();
        popularContato();
    }

    @Override
    public void salvar() {
        try {
            if (validarTela()) {
                pushToModel();

                if (mantemUsuario(usuario)) {
                    JOptionPane.showMessageDialog(rootPane, MensagensUtil.MENSAGEM_SUCESSO_CADASTRO, MensagensUtil.SUCESSO, 1);
                    disableTela(false);
                    btnEditar.setEnabled(true);
                    btnSalvar.setEnabled(false);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(FormUsuario.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, MessageUsuario.ERRO_SALVAR_USUARIO, MensagensUtil.ERRO, 0);
        }

    }

    @Override
    public void close() {
        if (!btnSalvar.isEnabled()) {
            fecharForm();
        } else {
            int opcao = JOptionPane.showOptionDialog(rootPane, MensagensUtil.MENSAGEM_CONFIRMAR_SAIR, MensagensUtil.ATENCAO,  
                JOptionPane.YES_NO_OPTION,  
                JOptionPane.QUESTION_MESSAGE, null, new String[]{"Sim", "Não"}, "Não"); 
            if (opcao == JOptionPane.YES_OPTION) {
                fecharForm();
            }
        }
    }

    private void fecharForm() {
        clear();
        this.dispose();
    }

    @Override
    public void initialize() {

        
        populaComboPerfil();
        createNew();

        //pular de campo com enter
        MetodosUtil.enterPularCampos(this);
        //define letras maiusculas
        MetodosUtil.letrasMaiusculas(this.getContentPane()); 

        //Logica para fechar tela pela botao do frame
        addListenerParaExibirMgsFecharTela();

        //Inicializa Acesso
        this.inicializaAcessoPorPerfil();
    }

    @Override
    public void clear() {
        txtLogin.setText(null);
        pswSenha.setText(null);
        pswConfirmarSenha.setText(null);
        cbPerfil.setSelectedIndex(0);

        clearPanelDadosPrincipais();
        clearPanelContato();
    }

    /**
     * Faz chamada ao server para salvar usuario
     * @param usuario
     * @return 
     */
    private boolean mantemUsuario(Usuario usuario) throws TransException {
        UsuarioServerImpl serverImpl = new UsuarioServerImpl();
        try {
            usuario = serverImpl.salvarUsuario(usuario);
        } catch (TransException ex) {
            throw ex;
        }

        return true;
    }

    /**********************
     * Disable  *INICIO*
     **********************/
    private void disableTela(boolean value) {
        txtLogin.setEnabled(value);
        pswSenha.setEnabled(value);
        pswConfirmarSenha.setEnabled(value);
        cbPerfil.setEnabled(value);

        disableDadosPrincipais(value);
        disableContato(value);
    }

    /**
     * Desabilita Dados Principais
     * @param value 
     */
    private void disableDadosPrincipais(boolean value) {
        txtNome.setEnabled(value);
        txtEndereco.setEnabled(value);
        txtNumero.setEnabled(value);
        txtComplemento.setEnabled(value);
        txtCidade.setEnabled(value);
        cbUF.setEnabled(value);
        jtxtCEP.setEnabled(value);
    }

    /**
     * Desabilita Contato
     * @param value 
     */
    private void disableContato(boolean value) {
        jtxtTelefoneResidencial.setEnabled(value);
        jtxtCelular1.setEnabled(value);
        cbOperadora1.setEnabled(value);
        jtxtTelefoneComercial.setEnabled(value);
        jtxtCelular2.setEnabled(value);
        cbOperadora2.setEnabled(value);

        jtxtEmail1.setEnabled(value);
        jtxtEmail2.setEnabled(value);
    }

    /**********************
     * Disable *FIM*
     **********************/
    /**
     * limpa os campos de dados principais
     */
    private void clearPanelDadosPrincipais() {
        txtNome.setText(null);
        txtEndereco.setText(null);
        txtNumero.setText(null);
        txtComplemento.setText(null);
        txtCidade.setText(null);
        cbUF.setSelectedIndex(0);
        jtxtCEP.setText(null);
    }

    /**
     * limpa os campos de contato
     */
    private void clearPanelContato() {
        jtxtTelefoneResidencial.setText(null);
        jtxtCelular1.setText(null);
        cbOperadora1.setSelectedIndex(0);
        jtxtTelefoneComercial.setText(null);
        jtxtCelular2.setText(null);
        cbOperadora2.setSelectedIndex(0);
        jtxtEmail1.setText(null);
        jtxtEmail2.setText(null);
    }

    /**********************
     * PushToModel *INICIO*
     **********************/
    /**
     * recupera os dados dá aba dados pricipais
     */
    private void pushToModelDadosPrincipais() {

        usuario.getPessoa().setNome(txtNome.getText());

        usuario.getPessoa().setEndereco(pushToModelEndereco(usuario.getPessoa()));

    }

    /**
     * Recupera os dados de endereço 
     * @return 
     */
    private Endereco pushToModelEndereco(Pessoa pessoa) {
        Endereco end = pessoa.getEndereco();
        if (end == null) {
            end = new Endereco();
        }
        end.setRua(txtEndereco.getText());
        end.setNumero(txtNumero.getText());
        end.setComplemento(txtComplemento.getText());
        end.setCidade(txtCidade.getText());
        if (cbUF.getSelectedIndex() != 0) {
            end.setEstado(cbUF.getSelectedItem().toString());
        } else
            end.setEstado(null);
        
        if (!jtxtCEP.getText().replace("-", "").trim().isEmpty()) {
            end.setCep(jtxtCEP.getText());
        } else
            end.setCep(null);

        end.setPessoa(pessoa);
        return end;
    }

    /**
     * Recupera os dados da aba contato
     */
    private void pushToModelContato() {
        usuario.getPessoa().setTelefones(returnListTelefones(usuario.getPessoa()));
        usuario.getPessoa().setEmails(returnListEmails(usuario.getPessoa()));
    }

    private Telefone buscaTelefonePorTipo(List<Telefone> list, int tipoTelefone, boolean celValid) {
        for (Telefone telefone : list) {
            if (telefone.getTipoTelefone() == tipoTelefone) {
                if (celValid) {
                    celValid = false;
                    continue;
                }
                return telefone;
            }
        }

        return new Telefone();
    }

    /**
     * Mosta a lista de telefones fornecidos na tela
     * @return 
     */
    private List<Telefone> returnListTelefones(Pessoa pessoa) {
        List<Telefone> list = new ArrayList<Telefone>();
        Telefone tel = null;

        //telefone Residencial
        if (!jtxtTelefoneResidencial.getText().replace("-", "").trim().isEmpty()) {
            tel = buscaTelefonePorTipo(pessoa.getTelefones(), Enum_TipoTelefone.RESIDENCIAL.getCodigo(), false);
            tel.setNumero(jtxtTelefoneResidencial.getText());
            tel.setOperadora(cbOperadora1.getSelectedItem().toString());
            tel.setTipoTelefone(Enum_TipoTelefone.RESIDENCIAL.getCodigo());
            tel.setPessoa(pessoa);
            list.add(tel);
        }

        //telefone Celular 1
        if (!jtxtCelular1.getText().replace("-", "").trim().isEmpty()) {
            tel = buscaTelefonePorTipo(pessoa.getTelefones(), Enum_TipoTelefone.CELULAR.getCodigo(), false);
            tel.setNumero(jtxtCelular1.getText());
            tel.setOperadora(cbOperadora1.getSelectedItem().toString());
            tel.setTipoTelefone(Enum_TipoTelefone.CELULAR.getCodigo());
            tel.setPessoa(pessoa);
            list.add(tel);
        }

        //telefone Comercial
        if (!jtxtTelefoneComercial.getText().replace("-", "").trim().isEmpty()) {
            tel = buscaTelefonePorTipo(pessoa.getTelefones(), Enum_TipoTelefone.COMERCIAL.getCodigo(), false);
            tel.setNumero(jtxtTelefoneComercial.getText());
            tel.setOperadora(cbOperadora2.getSelectedItem().toString());
            tel.setTipoTelefone(Enum_TipoTelefone.COMERCIAL.getCodigo());
            tel.setPessoa(pessoa);
            list.add(tel);
        }


        //telefone Celular 2
        if (!jtxtCelular2.getText().replace("-", "").trim().isEmpty()) {
            tel = buscaTelefonePorTipo(pessoa.getTelefones(), Enum_TipoTelefone.CELULAR.getCodigo(), true);
            tel.setNumero(jtxtCelular2.getText());
            tel.setOperadora(cbOperadora2.getSelectedItem().toString());
            tel.setTipoTelefone(Enum_TipoTelefone.CELULAR.getCodigo());
            tel.setPessoa(pessoa);
            list.add(tel);
        }

        return list;
    }

    private Email buscaEmail(List<Email> list, boolean segundoEmail) {
        for (Email email : list) {
            if (segundoEmail) {
                segundoEmail = false;
                continue;
            }
            return email;

        }

        return new Email();
    }

    /**
     * Monta a lista de email fornecidos na tela
     * @return 
     */
    private List<Email> returnListEmails(Pessoa pessoa) {
        List<Email> list = new ArrayList<Email>();
        Email email = null;
        if (!jtxtEmail1.getText().isEmpty()) {
            email = buscaEmail(pessoa.getEmails(), false);
            email.setEnderecoEmail(jtxtEmail1.getText());
            email.setPessoa(pessoa);
            list.add(email);
        }
        if (!jtxtEmail2.getText().isEmpty()) {
            email = buscaEmail(pessoa.getEmails(), true);
            email.setEnderecoEmail(jtxtEmail2.getText());
            email.setPessoa(pessoa);
            list.add(email);
        }

        return list;
    }

    /**********************
     * PushToModel *FIM*
     **********************/
    /**********************
     * PopularTela *INICIO*
     **********************/
    /**
     * Popula os campos de Dados Principais
     */
    private void popularDadosPrincipais() {
        txtNome.setText(usuario.getPessoa().getNome());
        popularEndereco(usuario.getPessoa().getEndereco());
    }

    /**
     * Popula os campos de Endereço
     * @param end 
     */
    private void popularEndereco(Endereco end) {
        txtEndereco.setText(end.getRua());
        txtNumero.setText(end.getNumero());
        txtComplemento.setText(end.getComplemento());
        txtCidade.setText(end.getCidade());
        cbUF.setSelectedItem(Enum_UF.getType(end.getEstado()));
        jtxtCEP.setText(end.getCep());
    }

    /**
     * Popula os campos de Contato
     */
    private void popularContato() {
        popularTelefones(usuario.getPessoa().getTelefones());
        popularEmail(usuario.getPessoa().getEmails());
    }

    /**
     * Popula os telefones na tela
     * @param list 
     */
    private void popularTelefones(List<Telefone> list) {
        for (Telefone telefone : list) {
            if (telefone.getTipoTelefone() == Enum_TipoTelefone.RESIDENCIAL.getCodigo()) {
                jtxtTelefoneResidencial.setText(telefone.getNumero());
            }
            if (telefone.getTipoTelefone() == Enum_TipoTelefone.CELULAR.getCodigo()) {
                if (jtxtCelular1.getText().replace("-", "").trim().isEmpty()) {
                    jtxtCelular1.setText(telefone.getNumero());
                    cbOperadora1.setSelectedIndex(returnEnumOperadoraTelefonica(telefone.getOperadora()));
                } else {
                    jtxtCelular2.setText(telefone.getNumero());
                    cbOperadora2.setSelectedIndex(returnEnumOperadoraTelefonica(telefone.getOperadora()));
                }
            }
            if (telefone.getTipoTelefone() == Enum_TipoTelefone.COMERCIAL.getCodigo()) {
                jtxtTelefoneComercial.setText(telefone.getNumero());
            }
        }
    }

    /**
     * retorna o valor da operadora selecionada
     * @param component
     * @return 
     */
    private int returnEnumOperadoraTelefonica(String operadora) {
        if (operadora.equals(OperadorasTelefonicas.VIVO)) {
            return 0;
        }
        if (operadora.equals(OperadorasTelefonicas.TIM)) {
            return 1;
        }
        if (operadora.equals(OperadorasTelefonicas.CLARO)) {
            return 2;
        } else {
            return 3;
        }
    }

    /**
     * Popular os campos Email
     * @param list 
     */
    private void popularEmail(List<Email> list) {
        for (Email email : list) {
            if (jtxtEmail1.getText().isEmpty()) {
                jtxtEmail1.setText(email.getEnderecoEmail());
            } else {
                jtxtEmail2.setText(email.getEnderecoEmail());
            }
        }
    }

    /**********************
     * PopularTela *FIM*
     **********************/
    /**
     * Buscar perfis
     */
    private List<Perfil> recPerfis() {

        List<Perfil> list = null;
        try {
            PerfilServerImpl serverImpl = new PerfilServerImpl();
            list = serverImpl.recListaPerfis(new Perfil());
        } catch (TransException ex) {
            Logger.getLogger(FormUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        return list;
    }

    private void populaComboPerfil() {
        listPerfil = recPerfis();
        cbPerfil.removeAllItems();
        cbPerfil.addItem("selecione");
        for (Perfil perfil : listPerfil) {
            cbPerfil.addItem(perfil.getNomePerfil());
        }
    }

    /**
     * Logica para quando o usuario clicar no botao fechar do frame
     * exibir a tela de confirmação
     */
    private void addListenerParaExibirMgsFecharTela() {
        //cancela acao do botao fechar
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

        //add windowsListener sobrescrevendo o metodo windowClosing
        addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                if (e.getID() == WindowEvent.WINDOW_CLOSING) {
                    close();
                }
            }
        });
    }

    @Override
    public void inicializaAcessoPorPerfil() {
        //this.btnEditar.setEnabled(ControleAcesso.ATIVA_BTN_CADASTRAR_USUARIO);
        if(!ControleAcesso.ATIVA_BTN_CADASTRAR_USUARIO)
            disableTela(false);
        this.btnSalvar.setEnabled(ControleAcesso.ATIVA_BTN_CADASTRAR_USUARIO);
        this.btnNovo.setEnabled(ControleAcesso.ATIVA_BTN_CADASTRAR_USUARIO);
        this.btnPesquisar.setEnabled(ControleAcesso.ATIVA_BTN_CONSULTAR_USUARIO);
    }
}
